-- ============================================================================
-- 05_example.sql
--   A base table, system versioning switched on, and the queries you get.
-- ============================================================================

CREATE TABLE IF NOT EXISTS employee (
    employee_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        text   NOT NULL,
    last_name         text   NOT NULL,
    department        text,
    salary            numeric(12,2) NOT NULL CHECK (salary >= 0),
    hired_on          date   NOT NULL DEFAULT current_date,
    -- populated by the versioning only; temporal.enable() would add the two
    -- period columns itself if they were left out here
    changed_by        name,
    sys_period_begin  timestamptz NOT NULL,
    sys_period_end    timestamptz NOT NULL
);

-- Creates employee_history (same columns, PK (employee_id, sys_period_begin))
-- plus the triggers. changed_by records who made each version, and on DELETE
-- a second, zero-length image records who deleted the row.
--
-- Also creates the query helpers:
--   employee_all                 view: employee UNION ALL employee_history
--   employee_as_of(timestamptz)  the state of the table at any point in time
SELECT temporal.enable('employee',
                       p_user_column  => 'changed_by',
                       p_delete_image => true);


-- ---------------------------------------------------------------- how to read
--
-- current rows                 : SELECT * FROM employee;
--
-- full timeline of one row     : SELECT * FROM employee_all
--                                WHERE employee_id = 1 ORDER BY sys_period_begin;
--
-- the table as of a timestamp  : SELECT * FROM employee_as_of(:ts);
--     which is
--     SELECT * FROM employee_all
--      WHERE sys_period_begin <= :ts AND sys_period_end > :ts;
--     (zero-length delete images never match)
--
-- rows deleted since a time, and by whom :
--     SELECT changed_by, sys_period_end, *
--       FROM employee_history
--      WHERE sys_period_begin = sys_period_end AND sys_period_end >= :ts;
-- ----------------------------------------------------------------------------
