-- ============================================================================
-- 05_example.sql
--   A main table, system versioning switched on, and the queries you get.
-- ============================================================================

CREATE TABLE IF NOT EXISTS employee (
    employee_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   text   NOT NULL,
    last_name    text   NOT NULL,
    department   text,
    salary       numeric(12,2) NOT NULL CHECK (salary >= 0),
    hired_on     date   NOT NULL DEFAULT current_date
);

-- Creates employee_history plus both triggers.
SELECT temporal.enable('employee');


-- ---------------------------------------------------------------- how to read
--
-- current rows                 : SELECT * FROM employee;
--
-- full timeline of one row     : SELECT * FROM employee_history
--                                WHERE employee_id = 1 ORDER BY valid_from;
--
-- the table as of a timestamp  :
--     SELECT <main columns>
--       FROM employee_history
--      WHERE valid_from <= :ts
--        AND (valid_to IS NULL OR valid_to > :ts);
--     (a row deleted after :ts is still visible; one deleted before is not,
--      because its last version was closed at delete time)
--
-- rows deleted since a time    :
--     SELECT * FROM employee_history
--      WHERE ended_by = 'DELETE' AND valid_to >= :ts;
--
-- who changed what, latest first:
--     SELECT changed_at, changed_by, operation, ended_by, *
--       FROM employee_history ORDER BY changed_at DESC;
-- ----------------------------------------------------------------------------

-- A convenience view: the state of the table at any point in time.
CREATE OR REPLACE FUNCTION employee_as_of(p_at timestamptz)
RETURNS SETOF employee
LANGUAGE sql STABLE
AS $$
    SELECT h.employee_id, h.first_name, h.last_name, h.department, h.salary, h.hired_on
      FROM employee_history h
     WHERE h.valid_from <= p_at
       AND (h.valid_to IS NULL OR h.valid_to > p_at);
$$;
